### ISSUE TITLE
Build fails due to missing React import

### ISSUE THREAD

**Issue by guido4000** [remix-run/starter-express#10]
VS Code already complains about the missing React imports in the modules and build fails due to the same issue.

```
 npm run build

> remix-starter-express@1.0.0 build /home/main/projects/remix/starter-express
> remix build && tsc -b

Building Remix app for production...
done!
app/App.tsx:7:6 - error TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.

7     <html lang="en">
       ~~~~

app/App.tsx:8:8 - error TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.

8       <head>
         ~~~~

**Comment by mjackson** [comment]
Thanks for the issue, but we are archiving this repo. We have a new `npm init remix` command that we are recommending people use to get started instead of the starter repos, so I'm closing all the issues here.

I haven't actually seen this specific issue before, but I hope you got it figured out! If not, please join our Discord server (the link is in the Support tab on remix.run) and we'll be happy to help you there.
