### ISSUE TITLE
Data not loading or is cached

### ISSUE THREAD

**Issue by beerify** [remix-run/starter-express#11]
I'm trying to follow the example in the docs and it seems that team is not getting written to data-build/routes despite being present in the same places as the gist example. `npm run dev` doesn't seem to build the app correctly

Update: I manually added team.js to data-build/routes and got the Team component to render, however this does not solve the build issue

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.loader = void 0;
let loader = async () => {
    return fetch("https://api.github.com/orgs/reacttraining/members");
};
exports.loader = loader;
```

**Comment by mjackson** [comment]
Thanks for the issue, but we are archiving this repo. We have a new `npm init remix` command that we are recommending people use to get started instead of the starter repos, so I'm closing all the issues here.

If you need help with this kind of thing, please join our Discord server (you can find the link in the support tab on remix.run) and we'll be happy to help you 👍
