### ISSUE TITLE
[0.8.1] Importing in data loader causes data-build directory to have incorrect structure

### ISSUE THREAD

**Issue by mdingena** [remix-run/starter-express#12]
I wanted to import some test JSON data.

```ts
// data/routes/cybermonday-blackfriday/index.ts
import type { Loader } from '@remix-run/data'
import * as data from '../../../json/test-items.json'

export const loader: Loader = () => {
  return data
}
```
As you can see, `json` directory is a sibling of `data` directory.

Running `tsc -b` now results in a `data-build` directory like:
```
data-build
├── data
│   ├── global.js
│   └── routes
│       ├── cybermonday-blackfriday
│       │   └── index.js
│       └── index.js
└── json
    └── test-items.json

4 directories, 4 files
```

Which causes some problems when launching Remix, as it's expecting a `data-build/routes` directory which is not there in this case.

Changing the data loader to
```ts
import type { Loader } from '@remix-run/data'
//import * as data from '../../../json/test-items.json'

export const loader: Loader = () => {
  return null
}
```

and rerunning `tsc -b`:

```
data-build
├── data
│   ├── global.js
│   └── routes
│       ├── cybermonday-blackfriday
│       │   └── index.js
│       └── index.js
├── global.js
├── json
│   └── test-items.json
└── routes
    ├── cybermonday-blackfriday
    │   └── index.js
    └── index.js

6 directories, 7 files
```

Which correctly outputs the `data-build/routes` directory but doesn't seem to clean up the previous build. Are we supposed to manually clean these up?

**Comment by mdingena** [comment]
Although in v0.13 we no longer have the `data-build` directory, the problem of leaving stale files between rebuilds still stands. It would be nicer if Remix purged the build dirs before rebuilding. Is there a reason this isn't done? Does that slow down rebuilds significantly? Should Remix users implement their own cleanup methods (pre-deployment, for example)?

**Comment by mjackson** [comment]
Thanks for the issue, but we are archiving this repo. We have a new `npm init remix` command that we are recommending people use to get started instead of the starter repos, so I'm closing all the issues here.

As far as cleaning up old builds goes, for now Remix doesn't do any of that. If I want a fresh build, I usually alias my build command to `rm -rf .cache build public/build && remix build`. We may be better about this in the future, but I'm a little hesitant to go removing files on the filesystem that you didn't explicitly ask me to remove. Hope that helps!
